// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6ccMyunwWvbi5lfLSx3QTs9hPwFe_sw',
    appId: '1:827492739358:web:57d74536176ece2155410f',
    messagingSenderId: '827492739358',
    projectId: 'ecommerce-221a0',
    authDomain: 'ecommerce-221a0.firebaseapp.com',
    storageBucket: 'ecommerce-221a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0-ZTT7uhVEtGYoxQqIdqahSH0zh20VI',
    appId: '1:827492739358:android:25b506179708771e55410f',
    messagingSenderId: '827492739358',
    projectId: 'ecommerce-221a0',
    storageBucket: 'ecommerce-221a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ny9amreDsBvYU7E2ZMCPfvp9MBF-fRs',
    appId: '1:827492739358:ios:d1e0a642a70ef89a55410f',
    messagingSenderId: '827492739358',
    projectId: 'ecommerce-221a0',
    storageBucket: 'ecommerce-221a0.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
